version: "2.27"
services:
    database:
        container_name: db_php
        image: mysql:8.0
        environment:
            - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
            - MYSQL_DATABASE=${DB_DATABASE}
            - MYSQL_ROOT_USER=${DB_USERNAME}
            - MYSQL_PASSWORD=${DB_PASSWORD}
        ports:
            - "3307:3306"
        volumes:
            - db_data:/var/lib/mysql
        command: php artisan serve --host=0.0.0.0 --port=8000
    php:
        container_name: php_app
        build:
            context: .
            target: php
            args:
                - APP_ENV=${APP_ENV}
        environment:
            - APP_ENV=${APP_ENV}
            - CONTAINER_ROLE=app
        working_dir: /var/www
        volumes:
            - .:/var/www
        ports:
            - "8000:8000"
            - ${VITE_PORT:-5173}:${VITE_PORT:-5173}
        depends_on:
            - database
        links:
            - database

volumes:
    db_data: ~